language: ruby
rvm:
- 2.4.1
deploy:
  api_key:
    secure: dlsyfCnk0ZtzNeESpmnFMXVjdkPsTV5plFWHo+oeGl+ohEjtbcVFpWNP8E74JMr9WxePOgQXGoxnjpox0fuuMlIkYv/AIM6+wjhAl8NBYoFMqJCZ9T0DOv2hInPprWH0HhHluyzcodAqNckMn71DyyB7FjadhhsV1IXIGI3G8T/0otSmwfevVv/8FfA6FnEMmy0HzgbdUEBIx9JogcvenojgoFKnLv8GFISqP13uRXlxM2hgVcTE64EVICzYrfKTBMzJmM18YFO85BYnDJ4rxFJUXiGdculP+2RUmZaX8tCWaPwHrV1DY08d3EtE9JOlI6EQTGhEF+we8QZhNRl6rRDHnjO5pBhXV4QJmYsrzC1jAOX3avEVsa5T/MTQYsw3yLHVNmEWQVjtvb/p8vHAv7BNQdk+qyI/Gb9lmEJzgC6aD4h7bcHeqpEPYzalSozFZWxFAA89QSjiI4iv59vDLwGHJCqvGNEZ+y63x0FRTUxC0wREg0wBPM2GboTk2npau0tHQrD/ZBz5AzlYViuNYBC4bqI8nwQW0ktF/243CY6MvQ5j/sRsnADqH4tunvUKi1KdnvzVjwNViHdoXV9pYAbuxebNLMdU23JVPEe6M9jihO2R9lZ1XrHfVhxxP2vACYIRlfBk9ehZVTdA9kkxEQW4fltZ15uLl98EGnTf/Fg=
